# Config for multi-device full finetuning in full_finetune_distributed.py
# using a Mistral Nemo 12B model


# Tokenizer
tokenizer:
  _component_: torchtune.models.mistral.mistral_hf_tokenizer
  path: /cephfs/SHARE/project/huggingface.co/hub/models--mistralai--Mistral-Nemo-Base-2407/snapshots/d613c787305d2300f41ad94abaec338411fbbecf/
  max_seq_len: 8192

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: json
  data_files: [
    /cephfs/GPT/usr/xuanshuzhe/code/data_process/chai_preference_data/processed_data/sft/v1/chai_preference_sft_train_data_llama3_v1.jsonl,
    /cephfs/GPT/usr/xuanshuzhe/code/data_process/ugc/memory/v1/fix_memory_answer_v5_llama3.jsonl
  ]
  conversation_column: dialogue
  conversation_style: haigpt
  train_on_input: False
  # packed: true
  packed: false
  split: train
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.mistral.mistral_nemo_12b

output_dir: ./output/mistral_nemo_12b_ugc_char_sft_low_mem_1025
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /cephfs/SHARE/project/huggingface.co/hub/models--mistralai--Mistral-Nemo-Base-2407/snapshots/d613c787305d2300f41ad94abaec338411fbbecf/
  # checkpoint_dir: /cephfs/SHARE/project/huggingface.co/hub/models--mistralai--Mistral-Nemo-Instruct-2407/snapshots/e17a136e1dcba9c63ad771f2c85c1c312c563e6b/
  checkpoint_files: [
    model-00001-of-00005.safetensors,
    model-00002-of-00005.safetensors,
    model-00003-of-00005.safetensors,
    model-00004-of-00005.safetensors,
    model-00005-of-00005.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: MISTRAL
resume_from_checkpoint: False

# Fine-tuning arguments
batch_size: 1
epochs: 3
optimizer:
  # _component_: bitsandbytes.optim.PagedAdamW
  _component_: torch.optim.AdamW
  lr: 2e-5
loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss
max_steps_per_epoch: null
# optimizer_in_bwd: True
gradient_accumulation_steps: 8
save_every_n_steps: 40
save_optimizer_state: False

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True
fsdp_cpu_offload: True
memory_efficient_fsdp_wrap: True

# Reduced precision
dtype: bf16

# Model compilation
compile: False

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.TensorBoardLogger
  log_dir: ${output_dir}
log_every_n_steps: 1
log_peak_memory_stats: False
