# Config for multi-device LoRA finetuning in lora_finetune_distributed.py
# using a Mistral Nemo 12B model
#
# This config uses hyperparameters based on small set of experiments and information
# available on various forums. These are not meant to replicate the numbers
# from the paper
#
# This config assumes that you've run the following command before launching
# this run:
#   tune download mistralai/Mistral-7B-v0.1 --hf-token <HF_TOKEN> --output-dir /tmp/Mistral-7B-v0.1
#
# Run this config on 2 GPUs using the following:
#   tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config mistral/7B_lora
#
# You can add specific overrides through the command line. For example
# to override the checkpointer directory while launching training
# you can run:
#   tune run --nnodes 1 --nproc_per_node 2 lora_finetune_distributed --config mistral/7B_lora checkpointer.checkpoint_dir=<YOUR_CHECKPOINT_DIR>
#
# This config works best when the model is being fine-tuned on 2+ GPUs.
# For single device LoRA finetuning please use 7B_lora_single_device.yaml
# or 7B_qlora_single_device.yaml for those cases


# Tokenizer
tokenizer:
  _component_: torchtune.models.mistral.mistral_hf_tokenizer
  path: /cephfs/SHARE/project/huggingface.co/hub/models--mistralai--Mistral-Nemo-Base-2407/snapshots/d613c787305d2300f41ad94abaec338411fbbecf/
  max_seq_len: 8192

# Dataset
dataset:
  _component_: torchtune.datasets.chat_dataset
  source: json
  data_files: [
    /cephfs/GPT/usr/xuanshuzhe/code/data_process/chai_preference_data/processed_data/sft/v1/chai_preference_sft_train_data_llama3_v1.jsonl,
    /cephfs/GPT/usr/xuanshuzhe/code/data_process/ugc/memory/v1/fix_memory_answer_v5_llama3.jsonl
  ]
  conversation_column: dialogue
  conversation_style: haigpt
  train_on_input: False
  packed: True
  split: train
seed: null
shuffle: True

# Model Arguments
model:
  _component_: torchtune.models.mistral.lora_mistral_nemo_12b
  lora_attn_modules: ['q_proj', 'k_proj', 'v_proj']
  apply_lora_to_mlp: True
  apply_lora_to_output: True
  lora_rank: 32
  lora_alpha: 16
  lora_dropout: 0.0

output_dir: /cephfs/GPT/usr/pangwenjie/her/haigpt/idea_tune/torchtune/recipes/output/mistral_nemo_12b_ugc_char_lora_1022
checkpointer:
  _component_: torchtune.training.FullModelHFCheckpointer
  checkpoint_dir: /cephfs/SHARE/project/huggingface.co/hub/models--mistralai--Mistral-Nemo-Base-2407/snapshots/d613c787305d2300f41ad94abaec338411fbbecf/
  checkpoint_files: [
    model-00001-of-00005.safetensors,
    model-00002-of-00005.safetensors,
    model-00003-of-00005.safetensors,
    model-00004-of-00005.safetensors,
    model-00005-of-00005.safetensors
  ]
  recipe_checkpoint: null
  output_dir: ${output_dir}
  model_type: MISTRAL
resume_from_checkpoint: False
save_adapter_weights_only: False

optimizer:
  _component_: torch.optim.AdamW
  fused: True
  lr: 5e-5

lr_scheduler:
  _component_: torchtune.training.lr_schedulers.get_cosine_schedule_with_warmup
  num_warmup_steps: 100

loss:
  _component_: torchtune.modules.loss.CEWithChunkedOutputLoss

# Fine-tuning arguments
batch_size: 1
epochs: 10
max_steps_per_epoch: null
gradient_accumulation_steps: 8
save_every_n_steps: 40
save_optimizer_state: False

# Training env
device: cuda

# Memory management
enable_activation_checkpointing: True

# Reduced precision
dtype: bf16

# Logging
metric_logger:
  _component_: torchtune.training.metric_logging.TensorBoardLogger
  log_dir: ${output_dir}/logs
log_every_n_steps: 1
log_peak_memory_stats: False
